### PR TITLE
Document decision to use Keycloak

### PR DESCRIPTION
**Pull request by ccremer**
My attempt at documenting decisions.
Basically it follows this structure:

* Problem: What are we trying to solve?
* Alternatives: What are our options?
* Decision: What have we decided?
* Rationale: Why did we choose the option?

Additionally, we provide links to:
* Requirements: Relevant requirements documentation.
* Dependent decisions: Some decisions depend on other decisions.

### CODE REVIEW

**Comment by ccremer** [comment]
(currently this PR contains changes from #1 , should be rebased once #1 is merged)

**Review by tobru — CHANGES_REQUESTED** [review]
Content OK, I'd also fill that under "Explanation".

**Comment by ccremer** [comment]
> I'd also fill that under "Explanation".

I think there will be dozens of documented decisions over the next few iterations. should we all keep them as separate pages? Or make them into one page using sections, or is it possible to create a sub-navigation under "explanation"?

I don't think that "explanation" should contain random bunch of decisions, requirements, diagrams, etc. That would be bad navigation experience since we can clearly group requirements and decisions.

**Comment by ccremer** [comment]
I forgot that indendet navigation is a thing. All good for me.

**Review by tobru — APPROVED** [review]

**Pull request merged**
