### PR TITLE
add mysql to appcat exoscale dbaas documentation

### PR DESCRIPTION
**Pull request by susana-garcia**
## Summary

Add new mysql class to appcat exoscale dbaas documentation

## Checklist

- [X] Try to isolate changes into separate PRs (to build a better changelog).
- [X] Categorize the PR by setting a good title and adding one of the labels:
      `change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
      as they show up in the changelog
- [X] Link this PR to related issues if applicable.

### CODE REVIEW

**Review by ZuGao — APPROVED** [review]
LGTM

**Comment by Kidswiss** [comment]
LGTM

Maybe one thought I had: would it make sense to introduce a class that handles all of dbaas for exoscale? So people don't have to import multiple classes every time?

**Review by Kidswiss — APPROVED** [review]

**Comment by susana-garcia** [comment]
> LGTM
> 
> Maybe one thought I had: would it make sense to introduce a class that handles all of dbaas for exoscale? So people don't have to import multiple classes every time?

I see what you mean, but I wouldn't that. The chances that customers need all of them at the once may not be high, plus it can create confusion of what dbaas are included. But I may be wrong, please let me know your thoughts about it.

**Comment by Kidswiss** [comment]
> I see what you mean, but I wouldn't that. The chances that customers need all of them at the once may not be high, plus it can create confusion of what dbaas are included. But I may be wrong, please let me know your thoughts about it.

My use-case is for appuio cloud, where we want all the services deployed. I'd actually argue that even on customer clusters everything should get deployed, even if they only use one service. Makes managing things easier.

**Comment by susana-garcia** [comment]
> > I see what you mean, but I wouldn't that. The chances that customers need all of them at the once may not be high, plus it can create confusion of what dbaas are included. But I may be wrong, please let me know your thoughts about it.
> 
> My use-case is for appuio cloud, where we want all the services deployed. I'd actually argue that even on customer clusters everything should get deployed, even if they only use one service. Makes managing things easier.

Oh, now I see what you meant. In that case I agree.
Should I then leave the PR open for now?

**Comment by Kidswiss** [comment]
> Oh, now I see what you meant. In that case I agree.
> Should I then leave the PR open for now?



> > > I see what you mean, but I wouldn't that. The chances that customers need all of them at the once may not be high, plus it can create confusion of what dbaas are included. But I may be wrong, please let me know your thoughts about it.
> > 
> > 
> > My use-case is for appuio cloud, where we want all the services deployed. I'd actually argue that even on customer clusters everything should get deployed, even if they only use one service. Makes managing things easier.
> 
> Oh, now I see what you meant. In that case I agree. Should I then leave the PR open for now?

No it's fine, it's something we'd have to plan and discuss first anyway.

You can go ahead and merge.

**Comment by susana-garcia** [comment]
> > Oh, now I see what you meant. In that case I agree.
> > Should I then leave the PR open for now?
> 
> > > > I see what you mean, but I wouldn't that. The chances that customers need all of them at the once may not be high, plus it can create confusion of what dbaas are included. But I may be wrong, please let me know your thoughts about it.
> > > 
> > > 
> > > My use-case is for appuio cloud, where we want all the services deployed. I'd actually argue that even on customer clusters everything should get deployed, even if they only use one service. Makes managing things easier.
> > 
> > 
> > Oh, now I see what you meant. In that case I agree. Should I then leave the PR open for now?
> 
> No it's fine, it's something we'd have to plan and discuss first anyway.
> 
> You can go ahead and merge.

Ok, no problem.

**Pull request merged**
